language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
before_script:
  - rm -f $HOME/.yarnrc.yml
  - yarn set version berry
  - echo "nodeLinker: node-modules" >> $HOME/.yarnrc.yml
  - yarn
script: yarn run test