language: node_js
node_js:
- "10"
- "11"
- "12"
- "13"
- "14"
before_script:
- npm install -g gulp typescript
script: 
- npm run test
after_success: 
- npm run coverage


# before_script:
#   - npm install -g yarn
#   - curl -o- -L https://yarnpkg.com/install.sh | bash
#   - export PATH="$HOME/.yarn/bin:$PATH"
#   - rm -f .yarnrc.yml
#   - yarn set version berry
#   - echo "nodeLinker: node-modules" >> .yarnrc.yml
#   - yarn -v
#   - yarn
# script:
#   - yarn run test